--------------------------------------------------------
--  DDL for Table QUOTES
--------------------------------------------------------

  CREATE TABLE "JSP"."QUOTES" 
   (	"SEQ" NUMBER, 
	"WRITER" VARCHAR2(100 BYTE), 
	"TEXT" VARCHAR2(1000 BYTE), 
	"IMG1" VARCHAR2(4000 BYTE) DEFAULT 'https://www.google.com/search', 
	"IMG2" VARCHAR2(4000 BYTE) DEFAULT 'https://www.google.com/search'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MYTS" ;
