--------------------------------------------------------
--  파일이 생성됨 - 일요일-8월-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RECOMMEND
--------------------------------------------------------

  CREATE TABLE "JSP"."RECOMMEND" 
   (	"REC_NO" NUMBER, 
	"BOARD_NO" NUMBER, 
	"REC_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MYTS" ;
REM INSERTING into JSP.RECOMMEND
SET DEFINE OFF;
Insert into JSP.RECOMMEND (REC_NO,BOARD_NO,REC_ID) values (59,13476,'a004');
Insert into JSP.RECOMMEND (REC_NO,BOARD_NO,REC_ID) values (60,13477,'a004');
Insert into JSP.RECOMMEND (REC_NO,BOARD_NO,REC_ID) values (54,13475,'a004');
Insert into JSP.RECOMMEND (REC_NO,BOARD_NO,REC_ID) values (58,13472,'a004');
Insert into JSP.RECOMMEND (REC_NO,BOARD_NO,REC_ID) values (61,13473,'a004');
Insert into JSP.RECOMMEND (REC_NO,BOARD_NO,REC_ID) values (62,13474,'a004');
Insert into JSP.RECOMMEND (REC_NO,BOARD_NO,REC_ID) values (89,13464,'a004');
Insert into JSP.RECOMMEND (REC_NO,BOARD_NO,REC_ID) values (88,13463,'a004');
Insert into JSP.RECOMMEND (REC_NO,BOARD_NO,REC_ID) values (75,11980,'a004');
Insert into JSP.RECOMMEND (REC_NO,BOARD_NO,REC_ID) values (78,10356,'a004');
Insert into JSP.RECOMMEND (REC_NO,BOARD_NO,REC_ID) values (79,9193,'a004');
Insert into JSP.RECOMMEND (REC_NO,BOARD_NO,REC_ID) values (80,9994,'a004');
Insert into JSP.RECOMMEND (REC_NO,BOARD_NO,REC_ID) values (81,12025,'a004');
Insert into JSP.RECOMMEND (REC_NO,BOARD_NO,REC_ID) values (82,12717,'a004');
Insert into JSP.RECOMMEND (REC_NO,BOARD_NO,REC_ID) values (83,13152,'a004');
--------------------------------------------------------
--  DDL for Index SYS_C007286
--------------------------------------------------------

  CREATE UNIQUE INDEX "JSP"."SYS_C007286" ON "JSP"."RECOMMEND" ("REC_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MYTS" ;
--------------------------------------------------------
--  Constraints for Table RECOMMEND
--------------------------------------------------------

  ALTER TABLE "JSP"."RECOMMEND" ADD PRIMARY KEY ("REC_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MYTS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECOMMEND
--------------------------------------------------------

  ALTER TABLE "JSP"."RECOMMEND" ADD CONSTRAINT "DELETE_WITH_BOARD" FOREIGN KEY ("BOARD_NO")
	  REFERENCES "JSP"."QUOTES" ("SEQ") ON DELETE CASCADE ENABLE;
  ALTER TABLE "JSP"."RECOMMEND" ADD CONSTRAINT "DELETE_WITH_MEMBER" FOREIGN KEY ("REC_ID")
	  REFERENCES "JSP"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
